import { DockModel } from "./dock.model";
import { LocationModel } from "./location.model";
import { OperationModel } from "./operation.model";
import { PartnerModel } from "./partner.model";
import { ProductModel } from "./product.model";
import { ResponseDataItem } from "./response-wrappers.types";
import { StatusListModel } from "./status-list.model";

export interface BookingModel {
  id?: number;
  firstName: string;
  lastName: string;
  identityDocumentNumber: string;
  bookingBy: number;
  email: string;
  timeSlot: string;
  phoneNumber: string;
  referenceNumber: string;
  updateKey?: string;
  removalKey?: string;
  comments: string;
  operation: ResponseDataItem<OperationModel> | number | null;
  schedulingDate: string;
  documents?: File[];
  phoneRegionCode: string;
  
  truckLicensePlateFront?: string;
  truckLicensePlateBack?: string;
  clientInstruction?: string;
  goodsNoticeNr?: string;
  customer?: ResponseDataItem<PartnerModel> | number | null;
  dock?: ResponseDataItem<DockModel> | number | null;
  location?: ResponseDataItem<LocationModel> | number | null;
  statusListStatus?: ResponseDataItem<StatusListModel> | number | null;
  articleNr?: number;
  PIN?: string;
  goodsSupplier?: string;
  goodsBuyer?: string; 
  goods?: ResponseDataItem<ProductModel> | number | null;
  goodsDate?: string;
  nomenclature?: string;
  ticketLoadNr: string;
  harvestYear?: number;
  quantity?: string;
  quantityBrut?: number;
  quantityNet?: number;
  quantityEmptyContainer?: number;
  country?: string;
  county?: string;
  loadingDate?: string;
  loadUnloadingPlace?: string;
  trailerType?: number;
  goodsDescription: string;
  packageType: number;
  oldDocuments: number[];
  supplierId?: number;
  goodsName?: string;
  seriesContainer?: string;
  statusContainer?: number;
}
