export enum IntegrationPermissionEnum {
    CREATE_BOOKINGS = 'CREATE_BOOKINGS',
    UPDATE_BOOKINGS = 'UPDATE_BOOKINGS',
    CANCEL_VISITS = 'CANCEL_VISITS',
    REJECT_VISITS = 'REJECT_VISITS',
    SET_VISIT_PLANNED = 'SET_VISIT_PLANNED',
    SET_VISIT_WAITING = 'SET_VISIT_WAITING',
    SET_VISIT_PENDING = 'SET_VISIT_PENDING',
    CHECKIN_VISITS = 'CHECKIN_VISITS',
    CHECKOUT_VISITS = 'CHECKOUT_VISITS',
    INITIATE_VALIDATION = 'INITIATE_VALIDATION',
    PARENT_LOCATION = 'PARENT_LOCATION',
}